name: scheduled

on:
  push:
    branches: [main]
  schedule:
    - cron: "05 04 * * *"
    - cron: "0 0 15 * *"
    - cron: "0 0/15 * * *"

jobs:
  run_weather_bot:
    name: Run Wakatime Bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Setup Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: 20.9.0

      - name: Clean Install NPM Dependencies
        run: npm i

      - name: Run the Bot
        run: node index.js
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY}}
          NOTION_DATABASE: ${{ secrets.NOTION_DATABASE}}
          NOTION_KEY: ${{ secrets.NOTION_KEY}}
          DAY_DB_ID: ${{ secrets.DAY_DB_ID}}
          PROJECT_DB_ID: ${{ secrets.PROJECT_DB_ID}}
